# Generated by Django 6.0.3 on 2026-04-02 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to='csc.staff'),
        ),
    ]
