# Generated by Django 6.0.3 on 2026-04-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0002_student_assigned_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='course_images/')),
                ('duration', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
