# Generated by Django 6.0.3 on 2026-04-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='Qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
